trigger:
- master
- sanjaiga/datacontainerpipeline

pool:
  vmImage: 'Ubuntu-16.04'

resources:
  repositories:
  - repository: PublicFork
    endpoint: github.com_sanjaiganesh
    type: github
    name: sanjaiganesh/azure-rest-api-specs
  - repository: PrivateFork
    endpoint: github.com_sanjaiganesh
    type: github
    name: sanjaiganesh/azure-rest-api-specs-pr

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: fedten

- checkout: PublicForm
- checkout: PrivateFork

##[group]Beginning of a group
##[warning]Warning message
##[error]Error message
##[debug]Debug-only text
##[command]Command-line being run
##[endgroup]